### PR TITLE
documentation on installing private modules

### PR DESCRIPTION
**Pull request by wayneashleyberry**
Adds documentation on installing private modules.

### CODE REVIEW

**Comment by wayneashleyberry** [comment]
> Did you try https://help.github.com/en/articles/virtual-environments-for-github-actions#github_token-secret?

Yeah, didn't work for me when trying to install _other_ modules — which makes sense given the scope like you said.

**Comment by mvdan** [comment]
I'm happy to merge this, if you address my other comment :)

**Comment by wayneashleyberry** [comment]
Sorry got distracted by `$JOB` @mvdan, hopefully this is better?

**Comment by mvdan** [comment]
Thanks, that's better. Please fix the conflicts and move the FAQ entry under the secrets one :)

**Comment by wayneashleyberry** [comment]
gonna re-open this, github's being super weird right now

**Pull request closed without merging**
